/**
 * Demo business dataset.
 *
 * IMPORTANT: every record here is FICTIONAL sample data created for the demo.
 * `data_provenance: 'demo_dataset'` is carried through the whole pipeline and
 * surfaced in the UI so no fabricated claim is ever presented as a verified fact
 * about a real company.
 *
 * Digital maturity is deliberately varied: a few businesses are genuinely strong
 * (they should score lower as leads), most have real, observable gaps.
 */

export const DEMO_BUSINESSES = [
  {
    business_id: 'BIZ-DEN-001',
    name: 'Bright Smile Dental Studio',
    industry: 'Dental',
    sub_industry: 'Dental clinic',
    location: 'Lahore, Pakistan',
    city: 'Lahore',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/bright-smile-dental',
    website_snapshot: 'bright-smile-dental.html',
    phone: '+92 42 3500 1100',
    email: 'hello@brightsmile.demo',
    employee_band: '5-15',
    listing_notes: 'Listing mentions 3 chairs, walk-in appointments only, closed Sundays.',
    listing_rating: 4.3,
    listing_review_count: 86,
    founded_year: 2016,
    social_profiles: ['facebook'],
    maturity_label: 'low',
  },
  {
    business_id: 'BIZ-DEN-002',
    name: 'Gulberg Orthodontics & Implants',
    industry: 'Dental',
    sub_industry: 'Specialist dental practice',
    location: 'Lahore, Pakistan',
    city: 'Lahore',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/gulberg-orthodontics',
    website_snapshot: 'gulberg-orthodontics.html',
    phone: '+92 42 3577 2200',
    email: 'front.desk@gulbergortho.demo',
    employee_band: '15-40',
    listing_notes: 'Listing highlights implant centre, two locations, hiring front-desk staff.',
    listing_rating: 4.7,
    listing_review_count: 214,
    founded_year: 2009,
    social_profiles: ['facebook', 'instagram'],
    maturity_label: 'medium',
  },
  {
    business_id: 'BIZ-DEN-003',
    name: 'Johar Town Family Dentistry',
    industry: 'Dental',
    sub_industry: 'Dental clinic',
    location: 'Lahore, Pakistan',
    city: 'Lahore',
    country: 'Pakistan',
    website: null,
    website_snapshot: null,
    phone: '+92 42 3520 8899',
    email: null,
    employee_band: '2-8',
    listing_notes: 'Directory listing only — no website URL on record. Appointments by phone.',
    listing_rating: 4.1,
    listing_review_count: 27,
    founded_year: 2019,
    social_profiles: ['facebook'],
    maturity_label: 'none',
  },
  {
    business_id: 'BIZ-RE-001',
    name: 'Northline Estates',
    industry: 'Real Estate',
    sub_industry: 'Residential brokerage',
    location: 'Lahore, Pakistan',
    city: 'Lahore',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/northline-estates',
    website_snapshot: 'northline-estates.html',
    phone: '+92 42 3111 4455',
    email: 'sales@northlineestates.demo',
    employee_band: '10-30',
    listing_notes: 'Listing mentions 40+ active listings and a 6-person sales team.',
    listing_rating: 4.0,
    listing_review_count: 52,
    founded_year: 2014,
    social_profiles: ['facebook', 'instagram', 'youtube'],
    maturity_label: 'low',
  },
  {
    business_id: 'BIZ-RE-002',
    name: 'Capital Vista Realtors',
    industry: 'Real Estate',
    sub_industry: 'Commercial & residential brokerage',
    location: 'Islamabad, Pakistan',
    city: 'Islamabad',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/capital-vista-realtors',
    website_snapshot: 'capital-vista-realtors.html',
    phone: '+92 51 2870 3300',
    email: 'info@capitalvista.demo',
    employee_band: '20-60',
    listing_notes: 'Listing mentions expansion into DHA Phase 5 and recent agent recruitment drive.',
    listing_rating: 4.5,
    listing_review_count: 143,
    founded_year: 2011,
    social_profiles: ['facebook', 'instagram', 'linkedin'],
    maturity_label: 'medium',
  },
  {
    business_id: 'BIZ-RE-003',
    name: 'Skyline Property Partners',
    industry: 'Real Estate',
    sub_industry: 'Property management',
    location: 'Islamabad, Pakistan',
    city: 'Islamabad',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/skyline-property-partners',
    website_snapshot: 'skyline-property-partners.html',
    phone: '+92 51 2299 7788',
    email: 'contact@skylinepp.demo',
    employee_band: '30-80',
    listing_notes: 'Listing describes a tenant portal and in-house maintenance dispatch team.',
    listing_rating: 4.6,
    listing_review_count: 98,
    founded_year: 2008,
    social_profiles: ['linkedin', 'facebook'],
    maturity_label: 'high',
  },
  {
    business_id: 'BIZ-ECM-001',
    name: 'Kurta Bazaar',
    industry: 'E-commerce',
    sub_industry: 'Apparel retail',
    location: 'Karachi, Pakistan',
    city: 'Karachi',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/kurta-bazaar',
    website_snapshot: 'kurta-bazaar.html',
    phone: '+92 21 3455 6677',
    email: 'orders@kurtabazaar.demo',
    employee_band: '5-20',
    listing_notes: 'Listing mentions 200+ SKUs, cash-on-delivery, order confirmations handled over WhatsApp.',
    listing_rating: 3.9,
    listing_review_count: 311,
    founded_year: 2020,
    social_profiles: ['instagram', 'facebook'],
    maturity_label: 'low',
  },
  {
    business_id: 'BIZ-ECM-002',
    name: 'HomeNest Living',
    industry: 'E-commerce',
    sub_industry: 'Home & furniture retail',
    location: 'Lahore, Pakistan',
    city: 'Lahore',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/homenest-living',
    website_snapshot: 'homenest-living.html',
    phone: '+92 42 3666 1212',
    email: 'support@homenest.demo',
    employee_band: '20-50',
    listing_notes: 'Listing mentions two warehouses and a returns backlog complaint theme in reviews.',
    listing_rating: 4.2,
    listing_review_count: 764,
    founded_year: 2018,
    social_profiles: ['instagram', 'facebook', 'youtube'],
    maturity_label: 'medium',
  },
  {
    business_id: 'BIZ-ECM-003',
    name: 'PureLeaf Organics',
    industry: 'E-commerce',
    sub_industry: 'Health & wellness DTC',
    location: 'Karachi, Pakistan',
    city: 'Karachi',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/pureleaf-organics',
    website_snapshot: 'pureleaf-organics.html',
    phone: '+92 21 3599 4141',
    email: 'care@pureleaf.demo',
    employee_band: '10-25',
    listing_notes: 'Listing mentions subscription boxes and an active loyalty programme.',
    listing_rating: 4.8,
    listing_review_count: 1290,
    founded_year: 2017,
    social_profiles: ['instagram', 'facebook', 'linkedin', 'youtube'],
    maturity_label: 'high',
  },
  {
    business_id: 'BIZ-EDU-001',
    name: 'Apex Academy of Sciences',
    industry: 'Education',
    sub_industry: 'Test-prep academy',
    location: 'Lahore, Pakistan',
    city: 'Lahore',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/apex-academy',
    website_snapshot: 'apex-academy.html',
    phone: '+92 42 3588 9090',
    email: 'admissions@apexacademy.demo',
    employee_band: '20-60',
    listing_notes: 'Listing mentions MDCAT/ECAT batches; admissions handled with paper forms.',
    listing_rating: 4.4,
    listing_review_count: 176,
    founded_year: 2012,
    social_profiles: ['facebook', 'youtube'],
    maturity_label: 'low',
  },
  {
    business_id: 'BIZ-EDU-002',
    name: 'LinguaBridge Institute',
    industry: 'Education',
    sub_industry: 'Language training',
    location: 'Islamabad, Pakistan',
    city: 'Islamabad',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/linguabridge-institute',
    website_snapshot: 'linguabridge-institute.html',
    phone: '+92 51 2555 3131',
    email: 'enroll@linguabridge.demo',
    employee_band: '10-30',
    listing_notes: 'Listing mentions IELTS prep and corporate training contracts.',
    listing_rating: 4.5,
    listing_review_count: 88,
    founded_year: 2015,
    social_profiles: ['facebook', 'instagram', 'linkedin'],
    maturity_label: 'medium',
  },
  {
    business_id: 'BIZ-EDU-003',
    name: 'CodeCrafters School of Tech',
    industry: 'Education',
    sub_industry: 'Vocational tech bootcamp',
    location: 'Karachi, Pakistan',
    city: 'Karachi',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/codecrafters-school',
    website_snapshot: 'codecrafters-school.html',
    phone: '+92 21 3477 2323',
    email: 'hello@codecrafters.demo',
    employee_band: '15-40',
    listing_notes: 'Listing mentions cohort-based bootcamps with an online LMS and job-placement desk.',
    listing_rating: 4.7,
    listing_review_count: 402,
    founded_year: 2019,
    social_profiles: ['linkedin', 'instagram', 'youtube', 'facebook'],
    maturity_label: 'high',
  },
  {
    business_id: 'BIZ-HLT-001',
    name: 'Wellspring Physiotherapy Centre',
    industry: 'Healthcare',
    sub_industry: 'Physiotherapy clinic',
    location: 'Lahore, Pakistan',
    city: 'Lahore',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/wellspring-physio',
    website_snapshot: 'wellspring-physio.html',
    phone: '+92 42 3544 6161',
    email: 'reception@wellspringphysio.demo',
    employee_band: '5-15',
    listing_notes: 'Listing mentions 6 therapists and home-visit services booked by phone.',
    listing_rating: 4.6,
    listing_review_count: 64,
    founded_year: 2017,
    social_profiles: ['facebook'],
    maturity_label: 'low',
  },
  {
    business_id: 'BIZ-HLT-002',
    name: 'MediTrust Diagnostics Lab',
    industry: 'Healthcare',
    sub_industry: 'Diagnostic laboratory',
    location: 'Islamabad, Pakistan',
    city: 'Islamabad',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/meditrust-diagnostics',
    website_snapshot: 'meditrust-diagnostics.html',
    phone: '+92 51 2344 8080',
    email: 'reports@meditrust.demo',
    employee_band: '40-120',
    listing_notes: 'Listing mentions home sample collection across 4 sectors and SMS report delivery.',
    listing_rating: 4.3,
    listing_review_count: 521,
    founded_year: 2010,
    social_profiles: ['facebook', 'linkedin'],
    maturity_label: 'medium',
  },
  {
    business_id: 'BIZ-PRO-001',
    name: 'Meridian Tax & Advisory',
    industry: 'Professional Services',
    sub_industry: 'Accounting & tax advisory',
    location: 'Lahore, Pakistan',
    city: 'Lahore',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/meridian-tax-advisory',
    website_snapshot: 'meridian-tax-advisory.html',
    phone: '+92 42 3599 1717',
    email: 'clients@meridiantax.demo',
    employee_band: '10-30',
    listing_notes: 'Listing mentions filing-season overload and manual client document collection.',
    listing_rating: 4.2,
    listing_review_count: 41,
    founded_year: 2013,
    social_profiles: ['linkedin'],
    maturity_label: 'low',
  },
  {
    business_id: 'BIZ-PRO-002',
    name: 'Vantage Legal Consultants',
    industry: 'Professional Services',
    sub_industry: 'Corporate law firm',
    location: 'Islamabad, Pakistan',
    city: 'Islamabad',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/vantage-legal',
    website_snapshot: 'vantage-legal.html',
    phone: '+92 51 2610 4040',
    email: 'office@vantagelegal.demo',
    employee_band: '15-45',
    listing_notes: 'Listing mentions corporate retainers and cross-border advisory work.',
    listing_rating: 4.4,
    listing_review_count: 33,
    founded_year: 2007,
    social_profiles: ['linkedin', 'facebook'],
    maturity_label: 'medium',
  },
  {
    business_id: 'BIZ-PRO-003',
    name: 'Forge Digital Agency',
    industry: 'Professional Services',
    sub_industry: 'Marketing agency',
    location: 'Karachi, Pakistan',
    city: 'Karachi',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/forge-digital-agency',
    website_snapshot: 'forge-digital-agency.html',
    phone: '+92 21 3588 1919',
    email: 'new.business@forgedigital.demo',
    employee_band: '25-70',
    listing_notes: 'Listing mentions retainer clients, in-house automation stack and a content team.',
    listing_rating: 4.9,
    listing_review_count: 187,
    founded_year: 2016,
    social_profiles: ['linkedin', 'instagram', 'facebook', 'youtube', 'twitter'],
    maturity_label: 'high',
  },
  {
    business_id: 'BIZ-PRO-004',
    name: 'Summit HR Solutions',
    industry: 'Professional Services',
    sub_industry: 'HR & recruitment consultancy',
    location: 'Lahore, Pakistan',
    city: 'Lahore',
    country: 'Pakistan',
    website: 'https://demo.firmscout.local/summit-hr-solutions',
    website_snapshot: 'summit-hr-solutions.html',
    phone: '+92 42 3512 2626',
    email: 'talent@summithr.demo',
    employee_band: '8-25',
    listing_notes: 'Listing mentions high-volume CV screening handled manually by two coordinators.',
    listing_rating: 4.0,
    listing_review_count: 19,
    founded_year: 2021,
    social_profiles: ['linkedin', 'facebook'],
    maturity_label: 'low',
  },
];

export const DEMO_SCENARIOS = [
  {
    scenario_id: 'dental-lahore',
    label: 'Dental Clinics — Lahore',
    description: 'Clinics that still book appointments over the phone and have little or no automation.',
    icp_form: {
      industry: 'Dental',
      location: 'Lahore, Pakistan',
      business_size: 'Small clinic, 2-40 staff',
      services_offered: 'Online appointment booking systems, WhatsApp reminder automation, patient CRM, website redesign',
      budget_range: 'PKR 150,000 - 600,000 per project',
    },
    description_text:
      'We sell appointment booking systems, WhatsApp reminder automation and patient CRMs to dental clinics in Lahore. Our best customers are clinics with 2-40 staff that still take bookings by phone, have no reminder system, and lose patients to no-shows. We are not a good fit for large hospital chains with in-house IT teams.',
  },
  {
    scenario_id: 'real-estate-lhr-isb',
    label: 'Real Estate — Lahore & Islamabad',
    description: 'Brokerages with listing sites but no lead capture or follow-up automation.',
    icp_form: {
      industry: 'Real Estate',
      location: 'Lahore, Islamabad, Pakistan',
      business_size: 'Agencies with 5-80 agents',
      services_offered: 'Lead capture landing pages, CRM implementation, automated lead follow-up, property listing portals',
      budget_range: 'PKR 300,000 - 1,500,000 per project',
    },
    description_text:
      'We build lead capture funnels, CRMs and automated follow-up sequences for real estate agencies in Lahore and Islamabad. Ideal clients run 5-80 agents, advertise on property portals, and lose inbound enquiries because follow-up is manual. Agencies that already run a mature CRM and tenant portal are a weaker fit.',
  },
  {
    scenario_id: 'ecommerce-pakistan',
    label: 'E-commerce — Pakistan',
    description: 'Online retailers running order confirmation and support manually.',
    icp_form: {
      industry: 'E-commerce',
      location: 'Pakistan',
      business_size: 'Online retailers doing 200+ orders per month',
      services_offered: 'Order automation, abandoned cart recovery, WhatsApp support bots, returns workflow automation',
      budget_range: 'PKR 200,000 - 900,000 per project',
    },
    description_text:
      'We sell order automation, abandoned cart recovery and WhatsApp support bots to Pakistani e-commerce brands doing 200+ orders a month. The best fit is a store where order confirmations, returns and customer questions are still handled by hand. Stores already running subscriptions, loyalty and full marketing automation are less of a fit.',
  },
  {
    scenario_id: 'education',
    label: 'Education & Training',
    description: 'Academies and institutes with paper-based admissions and manual student follow-up.',
    icp_form: {
      industry: 'Education',
      location: 'Pakistan',
      business_size: 'Academies and institutes with 10-100 staff',
      services_offered: 'Online admissions portals, student CRM, fee reminder automation, LMS integration',
      budget_range: 'PKR 250,000 - 1,200,000 per project',
    },
    description_text:
      'We implement online admissions portals, student CRMs and fee reminder automation for academies, institutes and training providers. Our best customers still collect admission forms on paper, chase fees by phone, and have no student database. Bootcamps that already run an LMS and placement pipeline are a weaker fit.',
  },
  {
    scenario_id: 'high-value-general',
    label: 'High-Value General ICP',
    description: 'Any established service business with clear digital gaps and real budget.',
    icp_form: {
      industry: 'Professional Services, Healthcare, Education, Real Estate',
      location: 'Pakistan',
      business_size: 'Established businesses, 10-120 staff',
      services_offered: 'Custom AI automation, workflow automation, CRM implementation, conversion-focused web builds',
      budget_range: 'PKR 500,000 - 3,000,000 per project',
    },
    description_text:
      'We sell custom AI and workflow automation plus conversion-focused web builds to established Pakistani businesses with 10-120 staff across professional services, healthcare, education and real estate. The strongest leads have real revenue, obvious manual processes, and a website that fails to convert. We avoid pre-revenue startups and businesses with no budget.',
  },
];
